### ISSUE TITLE
`exampleOimRadialRing.py` does not seem to fit properly[Bug]

### ISSUE THREAD

**Issue by amerand** [oimodeler/oimodeler#66]
**Describe the bug**
I ran `exampleOimRadialRing.py` and the emcee plots seem empty, with chi2 from -0.1 to 0.1 (?)

**To Reproduce**
run `exampleOimRadialRing.py`

**Expected behavior**
get converging emcee walkers, and models that fit the data. On the other hand, this example seem to fit a ring to the same data used to fit a binary in another example (`exampleOimFitterEmcee.py`)

**Screenshots**
<img width="865" alt="Screenshot 2024-07-26 at 06 17 20" src="https://github.com/user-attachments/assets/88ee6cdc-01d2-46ae-b4e7-5dcd7643dfe3">

<img width="765" alt="Screenshot 2024-07-26 at 06 18 08" src="https://github.com/user-attachments/assets/b2b8c452-95d6-411d-9eac-c5d5cb5f663a">

**Desktop (please complete the following information):**
- OS: mac OS
- Python 3.12.4, oimodeler 0.8.5, emcee 3.1.6

**Comment by AlexisMatter** [comment]
Hi Antoine,
thanks for raising this issue. Indeed, the ASPRO simulated dataset is clearly not adapted for that example, as well as the parameter space exploration. Moreover, the number of steps for the walkers is very low (due to the slowness of the 'hankel-type' models), which makes the walker plots look empty but actually there are just not enough steps.
I am working on that and let you know. 
Alexis

**Comment by AlexisMatter** [comment]
Dear Antoine,

I replaced the previous dataset by one that is much more adapted in the exampleOimRadialRing.py. In parallel, I implemented a faster version of the Hankel transform, which allows more steps to be run. You should get an excellent fit.
Finally, I also implemented another version of the radial ring model (oimRadialRing2) with the ring width as a parameter instead of the outer ring diameter (dout). There is also an example file of it (exampleOimRadialRing2.py) in the CustomModels directory.
Everything is in the 'feature-better-hankel' branch. I tested them and everything works fine. Marten, I think you can already merge this branch with the master branch.

Alexis
